/**
 * `/llms.txt`: the site in one page of plain text, for answer engines and
 * agents that read a site before they read its pages.
 *
 * Every number here comes from `facts.json` and the wasm record, the same
 * sources the pages read, so this file cannot say something the site does
 * not. It is built, not authored, for the same reason nothing on the site is
 * typed by hand.
 */
import type { APIRoute } from "astro";
import facts from "../generated/facts.json";
import { tourSections, wasmProvenance } from "../playground/samples";
import { latestRelease } from "../lib/release";
import platforms from "../generated/targets.json";
import { SPELLED } from "../lib/lessons";

export const GET: APIRoute = ({ site }) => {
  const origin = (site ?? new URL("https://iyi-lang.com")).href.replace(/\/$/, "");
  const loop = facts.recorded.edit_loop;
  const bin = facts.recorded.hello_binary;
  const pack = facts.recorded.context_pack;
  const s = facts.structural;
  const release = latestRelease();

  /* The platforms README.md says are run every build, and how each is run,
   * out of scripts/targets.mjs. This file is read by agents, so a stale
   * count here is worse than one on a page. */
  const ranCount = SPELLED[platforms.ran.length];
  const ranHow = platforms.ran.map((t) => platforms.how[t as keyof typeof platforms.how]);

  const tour = tourSections
    .map(
      (section) =>
        `- ${section.title}: ${section.steps.map((step) => `[${step.id}](${origin}/playground/${step.id}/)`).join(", ")}`,
    )
    .join("\n");

  const text = `# iyi

> A friendly, fast programming language for people and their agents. Compiled,
> native through LLVM, compatible with Crystal, and built so that a compiler is
> something an agent can talk to.

iyi is Turkish for "good". Source: https://github.com/iyilang/iyi (Apache 2.0).
Site: ${origin}. Latest release: ${release.version}, ${release.date}.

## What it is

One rule, four sides. A module is the unit of compilation and it compiles
against its dependencies' declarations, never their bodies (R-1). Everything a
module exports writes its types down (R-2). \`using\` brings exported names into
a file because that file asked (R-2b). There are no open classes; \`impl Trait
for Type\` lives with the trait or the type (R-3).

- Developer experience: change one line in a ${s.generated.toLocaleString("en-GB")}-line project of 30
  modules and rebuild in ${loop.best.iyi} s, against ${loop.best.crystal} s under Crystal's rules on the
  same compiler binary: about ${loop.claim.value}x less. Measured by \`${loop.command}\`
  on ${loop.machine}.
- AI experience: a module's interface is a file (.iyimod). \`iyi mod context\`
  grounds an edit at ${pack.size_low} to ${pack.size_high}% of the sources' size; a model writing
  against it spent ${pack.tokens_low} to ${pack.tokens_high}% fewer prompt tokens over ${pack.runs} measured
  runs (\`${pack.command}\`). The loop is one verb per step: \`iyi check -f json\`
  (verdict as data with suggested_edit spans), \`iyi fix\`, \`iyi test
  --affected\`, \`iyi run --sandbox\`, and \`iyi mcp\` / \`iyi lsp\` serving the
  same verbs over MCP and LSP.
- Portability: compiles for ${s.targets} targets and is run on ${ranCount} every
  build (${ranHow.join(", ")}).
- Performance and efficiency: native code through LLVM; a hello world is
  ${bin.iyi.kb} KB and starts in ${bin.iyi.ms} ms, against ${bin.crystal.kb.toLocaleString("en-GB")} KB and ${bin.crystal.ms} ms with Crystal's
  library (\`${bin.command}\` on ${bin.machine}).

## Install

    curl -fsSL https://raw.githubusercontent.com/iyilang/iyi/master/install.sh | sh
    ~/.local/bin/iyi run ~/.local/share/iyi/samples/hello.iyi

The latest release into ~/.local, on Linux x86-64 or macOS arm64, with both
libraries and the samples. Details: ${origin}/install/

## Crystal compatibility

The same compiler builds .cr files unchanged. \`iyi build --crystal\` gives an
iyi program Crystal's standard library, \`require\`, and shards (Kemal, db,
ameba, sqlite3 among those swept through it). A Crystal program cannot require
an iyi module; iyi consumes Crystal, not the other way round.

## Pages

- [Home](${origin}/): the one line, a listing that runs, the Crystal section.
- [Why iyi](${origin}/why/): the four sides, each with its measurement and machine.
- [Learn](${origin}/learn/): five lessons on the rule, each running a real program.
- [Install](${origin}/install/): the one-line installer, the by-hand version, and from source.
- [Playground](${origin}/playground/): the tour, ${tourSections.reduce((n, x) => n + x.steps.length, 0)} short programs that run in the browser.
- [Playground evidence](${origin}/playground/evidence/): what ran, what checked it.

The design record and the release notes are not on this site: SPEC.md and
CHANGELOG.md are read in the repository, which is where they are kept current.

## The tour

${tour}

## Provenance

Numbers generated by ${facts.provenance.generator} from the iyi repository at
${facts.provenance.commit}. Programs recorded by ${wasmProvenance.compiler} at
${wasmProvenance.commit.slice(0, 12)}. Where iyi loses is published on the why
page beside where it wins.
`;

  return new Response(text, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
};
